-- JTF-P1-E05..E10 commercial revision graph. Amounts are exact numeric values; rules are inert JSON ASTs.
CREATE TYPE opportunity_status AS ENUM('OPEN','QUALIFIED','PROPOSAL','WON','LOST','CANCELLED');
CREATE TYPE ctr_status AS ENUM('DRAFT','SUBMITTED','APPROVED','REJECTED');
CREATE TYPE technical_solution_status AS ENUM('DRAFT','FINAL');
CREATE TYPE quote_status AS ENUM('DRAFT','PENDING_APPROVAL','APPROVED','ISSUED','EXPIRED','REJECTED');
CREATE TYPE approval_decision AS ENUM('APPROVED','REJECTED');

CREATE TABLE commercial_currencies(code char(3) PRIMARY KEY CHECK(code ~ '^[A-Z]{3}$'), decimal_places smallint NOT NULL CHECK(decimal_places BETWEEN 0 AND 6));
CREATE TABLE commercial_units(code text PRIMARY KEY CHECK(code ~ '^[A-Z][A-Z0-9_]{0,15}$'), dimension text NOT NULL CHECK(length(trim(dimension))>0));
INSERT INTO commercial_currencies VALUES ('CNY',2),('USD',2),('EUR',2),('JPY',0);
INSERT INTO commercial_units VALUES ('EA','COUNT'),('KG','MASS'),('M','LENGTH'),('M2','AREA'),('HOUR','TIME');

CREATE TABLE opportunities(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, customer_id uuid, lead_id uuid,
 name text NOT NULL CHECK(length(trim(name)) BETWEEN 1 AND 200), status opportunity_status NOT NULL DEFAULT 'OPEN',
 owner_id uuid NOT NULL, owner_organization_id uuid NOT NULL, value numeric(24,6) NOT NULL CHECK(value>=0), currency char(3) NOT NULL,
 probability_basis_points integer NOT NULL CHECK(probability_basis_points BETWEEN 0 AND 10000), expected_close_date date NOT NULL,
 version integer NOT NULL DEFAULT 1 CHECK(version>0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
 created_by uuid NOT NULL, updated_by uuid NOT NULL, UNIQUE(id,tenant_id),
 FOREIGN KEY(tenant_id) REFERENCES organizations(id), FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),
 FOREIGN KEY(lead_id,tenant_id) REFERENCES leads(id,tenant_id), FOREIGN KEY(owner_id,tenant_id) REFERENCES employees(id,company_id),
 FOREIGN KEY(owner_organization_id,tenant_id) REFERENCES organizations(id,owner_organization_id), FOREIGN KEY(currency) REFERENCES commercial_currencies(code),
 FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id), FOREIGN KEY(updated_by,tenant_id) REFERENCES employees(id,company_id),
 CHECK(customer_id IS NOT NULL OR lead_id IS NOT NULL)
);
CREATE INDEX opportunities_scope_idx ON opportunities(tenant_id,owner_id,owner_organization_id,status,updated_at DESC,id) WHERE deleted_at IS NULL;
CREATE TABLE opportunity_lifecycle_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, opportunity_id uuid NOT NULL, from_status opportunity_status NOT NULL, to_status opportunity_status NOT NULL, actor_id uuid NOT NULL, reason text NOT NULL CHECK(length(trim(reason))>0), occurred_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(opportunity_id,tenant_id) REFERENCES opportunities(id,tenant_id), FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id));

CREATE TABLE ctrs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, opportunity_id uuid NOT NULL, code text NOT NULL, version integer NOT NULL DEFAULT 1 CHECK(version>0), created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,code), FOREIGN KEY(opportunity_id,tenant_id) REFERENCES opportunities(id,tenant_id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE ctr_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, ctr_id uuid NOT NULL, version integer NOT NULL CHECK(version>0), status ctr_status NOT NULL DEFAULT 'DRAFT', title text NOT NULL CHECK(length(trim(title)) BETWEEN 1 AND 200), requirements jsonb NOT NULL CHECK(jsonb_typeof(requirements)='object'), snapshot_hash char(64), submitted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,ctr_id,version), FOREIGN KEY(ctr_id,tenant_id) REFERENCES ctrs(id,tenant_id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id), CHECK((status='DRAFT' AND submitted_at IS NULL AND snapshot_hash IS NULL) OR (status<>'DRAFT' AND submitted_at IS NOT NULL AND snapshot_hash IS NOT NULL)));
CREATE TABLE ctr_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, ctr_version_id uuid NOT NULL, decision approval_decision NOT NULL, approver_id uuid NOT NULL, reason text NOT NULL, decided_at timestamptz NOT NULL DEFAULT now(), idempotency_key text NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 128), UNIQUE(tenant_id,idempotency_key), FOREIGN KEY(ctr_version_id,tenant_id) REFERENCES ctr_versions(id,tenant_id), FOREIGN KEY(approver_id,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE ctr_attachment_links(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, ctr_version_id uuid NOT NULL, attachment_id uuid NOT NULL, linked_by uuid NOT NULL, linked_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,ctr_version_id,attachment_id), FOREIGN KEY(ctr_version_id,tenant_id) REFERENCES ctr_versions(id,tenant_id), FOREIGN KEY(attachment_id,tenant_id) REFERENCES attachments(id,tenant_id), FOREIGN KEY(linked_by,tenant_id) REFERENCES employees(id,company_id));

CREATE TABLE technical_solutions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, opportunity_id uuid NOT NULL, code text NOT NULL, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,code), FOREIGN KEY(opportunity_id,tenant_id) REFERENCES opportunities(id,tenant_id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE technical_solution_revisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, technical_solution_id uuid NOT NULL, revision integer NOT NULL CHECK(revision>0), status technical_solution_status NOT NULL DEFAULT 'DRAFT', ctr_version_id uuid NOT NULL, specification jsonb NOT NULL CHECK(jsonb_typeof(specification)='object'), assumptions jsonb NOT NULL CHECK(jsonb_typeof(assumptions)='array'), created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,technical_solution_id,revision), FOREIGN KEY(technical_solution_id,tenant_id) REFERENCES technical_solutions(id,tenant_id), FOREIGN KEY(ctr_version_id,tenant_id) REFERENCES ctr_versions(id,tenant_id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));

CREATE TABLE cost_models(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, code text NOT NULL, name text NOT NULL, version integer NOT NULL DEFAULT 1, deleted_at timestamptz, created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,code), FOREIGN KEY(tenant_id) REFERENCES organizations(id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE cost_model_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, cost_model_id uuid NOT NULL, version integer NOT NULL CHECK(version>0), status definition_status NOT NULL DEFAULT 'DRAFT', currency char(3) NOT NULL, rules jsonb NOT NULL CHECK(jsonb_typeof(rules)='array'), published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,cost_model_id,version), FOREIGN KEY(cost_model_id,tenant_id) REFERENCES cost_models(id,tenant_id), FOREIGN KEY(currency) REFERENCES commercial_currencies(code), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE cost_sheet_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, cost_model_version_id uuid NOT NULL, technical_solution_revision_id uuid NOT NULL, input_hash char(64) NOT NULL, canonical_input jsonb NOT NULL CHECK(jsonb_typeof(canonical_input)='object'), currency char(3) NOT NULL, subtotal numeric(24,6) NOT NULL, total numeric(24,6) NOT NULL, trace jsonb NOT NULL CHECK(jsonb_typeof(trace)='array'), evaluated_at timestamptz NOT NULL DEFAULT now(), evaluated_by uuid NOT NULL, idempotency_key text NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 128), UNIQUE(id,tenant_id), UNIQUE(tenant_id,idempotency_key), FOREIGN KEY(cost_model_version_id,tenant_id) REFERENCES cost_model_versions(id,tenant_id), FOREIGN KEY(technical_solution_revision_id,tenant_id) REFERENCES technical_solution_revisions(id,tenant_id), FOREIGN KEY(currency) REFERENCES commercial_currencies(code), FOREIGN KEY(evaluated_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE cost_sheet_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, decision_id uuid NOT NULL, line_number integer NOT NULL CHECK(line_number>0), description text NOT NULL, quantity numeric(24,6) NOT NULL CHECK(quantity>=0), unit_code text NOT NULL, unit_cost numeric(24,6) NOT NULL CHECK(unit_cost>=0), total numeric(24,6) NOT NULL CHECK(total>=0), applied_rule_versions jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(applied_rule_versions)='array'), UNIQUE(tenant_id,decision_id,line_number), FOREIGN KEY(decision_id,tenant_id) REFERENCES cost_sheet_decisions(id,tenant_id), FOREIGN KEY(unit_code) REFERENCES commercial_units(code));

CREATE TABLE sales_policies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, code text NOT NULL, name text NOT NULL, version integer NOT NULL DEFAULT 1, deleted_at timestamptz, created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,code), FOREIGN KEY(tenant_id) REFERENCES organizations(id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE sales_policy_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, sales_policy_id uuid NOT NULL, version integer NOT NULL CHECK(version>0), status definition_status NOT NULL DEFAULT 'DRAFT', rules jsonb NOT NULL CHECK(jsonb_typeof(rules)='array'), published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,sales_policy_id,version), FOREIGN KEY(sales_policy_id,tenant_id) REFERENCES sales_policies(id,tenant_id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE sales_policy_evaluations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, sales_policy_version_id uuid NOT NULL, cost_decision_id uuid NOT NULL, input_hash char(64) NOT NULL, canonical_input jsonb NOT NULL CHECK(jsonb_typeof(canonical_input)='object'), passed boolean NOT NULL, approval_required boolean NOT NULL, minimum_margin_basis_points integer, maximum_discount_basis_points integer, reasons jsonb NOT NULL CHECK(jsonb_typeof(reasons)='array'), trace jsonb NOT NULL CHECK(jsonb_typeof(trace)='array'), evaluated_at timestamptz NOT NULL DEFAULT now(), evaluated_by uuid NOT NULL, idempotency_key text NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,idempotency_key), FOREIGN KEY(sales_policy_version_id,tenant_id) REFERENCES sales_policy_versions(id,tenant_id), FOREIGN KEY(cost_decision_id,tenant_id) REFERENCES cost_sheet_decisions(id,tenant_id), FOREIGN KEY(evaluated_by,tenant_id) REFERENCES employees(id,company_id));

CREATE TABLE quotes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quote_number text NOT NULL, opportunity_id uuid NOT NULL, version integer NOT NULL DEFAULT 1 CHECK(version>0), created_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,quote_number), FOREIGN KEY(opportunity_id,tenant_id) REFERENCES opportunities(id,tenant_id), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE quote_revisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quote_id uuid NOT NULL, revision integer NOT NULL CHECK(revision>0), status quote_status NOT NULL DEFAULT 'DRAFT', opportunity_version integer NOT NULL CHECK(opportunity_version>0), ctr_version_id uuid NOT NULL, technical_solution_revision_id uuid NOT NULL, cost_decision_id uuid NOT NULL, sales_policy_version_id uuid NOT NULL, sales_policy_evaluation_id uuid NOT NULL, currency char(3) NOT NULL, subtotal numeric(24,6) NOT NULL CHECK(subtotal>=0), discount numeric(24,6) NOT NULL CHECK(discount>=0), total numeric(24,6) NOT NULL CHECK(total>=0), cost_total numeric(24,6) NOT NULL CHECK(cost_total>=0), margin numeric(24,6) NOT NULL, margin_basis_points integer NOT NULL, valid_until timestamptz NOT NULL, issued_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,quote_id,revision), FOREIGN KEY(quote_id,tenant_id) REFERENCES quotes(id,tenant_id), FOREIGN KEY(ctr_version_id,tenant_id) REFERENCES ctr_versions(id,tenant_id), FOREIGN KEY(technical_solution_revision_id,tenant_id) REFERENCES technical_solution_revisions(id,tenant_id), FOREIGN KEY(cost_decision_id,tenant_id) REFERENCES cost_sheet_decisions(id,tenant_id), FOREIGN KEY(sales_policy_version_id,tenant_id) REFERENCES sales_policy_versions(id,tenant_id), FOREIGN KEY(sales_policy_evaluation_id,tenant_id) REFERENCES sales_policy_evaluations(id,tenant_id), FOREIGN KEY(currency) REFERENCES commercial_currencies(code), FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id), CHECK(total=subtotal-discount), CHECK(margin=total-cost_total), CHECK((status='ISSUED')=(issued_at IS NOT NULL)));
CREATE TABLE quote_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quote_revision_id uuid NOT NULL, line_number integer NOT NULL CHECK(line_number>0), description text NOT NULL, quantity numeric(24,6) NOT NULL CHECK(quantity>0), unit_code text NOT NULL, unit_price numeric(24,6) NOT NULL CHECK(unit_price>=0), total numeric(24,6) NOT NULL CHECK(total>=0), UNIQUE(tenant_id,quote_revision_id,line_number), FOREIGN KEY(quote_revision_id,tenant_id) REFERENCES quote_revisions(id,tenant_id), FOREIGN KEY(unit_code) REFERENCES commercial_units(code));
CREATE TABLE quote_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quote_revision_id uuid NOT NULL, decision approval_decision NOT NULL, approver_id uuid NOT NULL, reason text NOT NULL, decided_at timestamptz NOT NULL DEFAULT now(), idempotency_key text NOT NULL, UNIQUE(tenant_id,idempotency_key), FOREIGN KEY(quote_revision_id,tenant_id) REFERENCES quote_revisions(id,tenant_id), FOREIGN KEY(approver_id,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE quote_issued_snapshots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, quote_revision_id uuid NOT NULL, snapshot jsonb NOT NULL CHECK(jsonb_typeof(snapshot)='object'), snapshot_hash char(64) NOT NULL, issued_by uuid NOT NULL, issued_at timestamptz NOT NULL DEFAULT now(), idempotency_key text NOT NULL, UNIQUE(tenant_id,quote_revision_id), UNIQUE(tenant_id,idempotency_key), FOREIGN KEY(quote_revision_id,tenant_id) REFERENCES quote_revisions(id,tenant_id), FOREIGN KEY(issued_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE commercial_command_results(tenant_id uuid NOT NULL REFERENCES organizations(id), idempotency_key text NOT NULL CHECK(length(idempotency_key) BETWEEN 1 AND 128), command_type text NOT NULL, subject_id uuid NOT NULL, payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object'), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,idempotency_key));

CREATE FUNCTION protect_commercial_frozen_row() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'commercial decision/history is immutable'; END $$;
CREATE FUNCTION protect_ctr_version() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status<>'DRAFT' THEN RAISE EXCEPTION 'submitted CTR version is immutable'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
CREATE FUNCTION protect_quote_revision() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status='ISSUED' THEN RAISE EXCEPTION 'issued quote revision is immutable'; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
CREATE FUNCTION validate_technical_solution_ctr_pin() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM ctr_versions cv WHERE cv.id=NEW.ctr_version_id AND cv.tenant_id=NEW.tenant_id AND cv.status IN('SUBMITTED','APPROVED')) THEN RAISE EXCEPTION 'technical solution requires exact submitted CTR version'; END IF;
 RETURN NEW;
END $$;
CREATE FUNCTION validate_cost_decision_pins() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM cost_model_versions cmv WHERE cmv.id=NEW.cost_model_version_id AND cmv.tenant_id=NEW.tenant_id AND cmv.status='PUBLISHED') THEN RAISE EXCEPTION 'cost decision requires published model version'; END IF;
 RETURN NEW;
END $$;
CREATE FUNCTION validate_policy_evaluation_pins() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM sales_policy_versions spv WHERE spv.id=NEW.sales_policy_version_id AND spv.tenant_id=NEW.tenant_id AND spv.status='PUBLISHED') THEN RAISE EXCEPTION 'policy evaluation requires published policy version'; END IF;
 RETURN NEW;
END $$;
CREATE FUNCTION validate_quote_revision_pins() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE q_opportunity uuid; solution_ctr uuid; evaluation_policy uuid; evaluation_cost uuid; BEGIN
 SELECT opportunity_id INTO q_opportunity FROM quotes WHERE id=NEW.quote_id AND tenant_id=NEW.tenant_id;
 SELECT ctr_version_id INTO solution_ctr FROM technical_solution_revisions WHERE id=NEW.technical_solution_revision_id AND tenant_id=NEW.tenant_id;
 SELECT sales_policy_version_id,cost_decision_id INTO evaluation_policy,evaluation_cost FROM sales_policy_evaluations WHERE id=NEW.sales_policy_evaluation_id AND tenant_id=NEW.tenant_id;
 IF q_opportunity IS NULL OR NOT EXISTS(SELECT 1 FROM opportunities WHERE id=q_opportunity AND tenant_id=NEW.tenant_id AND version=NEW.opportunity_version) THEN RAISE EXCEPTION 'quote requires exact opportunity version'; END IF;
 IF solution_ctr IS DISTINCT FROM NEW.ctr_version_id THEN RAISE EXCEPTION 'quote CTR and technical solution pins disagree'; END IF;
 IF evaluation_policy IS DISTINCT FROM NEW.sales_policy_version_id OR evaluation_cost IS DISTINCT FROM NEW.cost_decision_id THEN RAISE EXCEPTION 'quote policy decision pins disagree'; END IF;
 IF NEW.status='ISSUED' AND (NEW.valid_until<=now() OR NOT EXISTS(SELECT 1 FROM sales_policy_evaluations spe WHERE spe.id=NEW.sales_policy_evaluation_id AND spe.tenant_id=NEW.tenant_id AND spe.passed) OR (EXISTS(SELECT 1 FROM sales_policy_evaluations spe WHERE spe.id=NEW.sales_policy_evaluation_id AND spe.tenant_id=NEW.tenant_id AND spe.approval_required) AND NOT EXISTS(SELECT 1 FROM quote_approvals qa WHERE qa.quote_revision_id=NEW.id AND qa.tenant_id=NEW.tenant_id AND qa.decision='APPROVED'))) THEN RAISE EXCEPTION 'quote issue validity or approval gate failed'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER opportunity_lifecycle_history_immutable BEFORE UPDATE OR DELETE ON opportunity_lifecycle_history FOR EACH ROW EXECUTE FUNCTION protect_commercial_frozen_row();
CREATE TRIGGER ctr_versions_frozen_guard BEFORE UPDATE OR DELETE ON ctr_versions FOR EACH ROW EXECUTE FUNCTION protect_ctr_version();
CREATE TRIGGER ctr_approvals_immutable BEFORE UPDATE OR DELETE ON ctr_approvals FOR EACH ROW EXECUTE FUNCTION protect_commercial_frozen_row();
CREATE TRIGGER technical_solution_ctr_pin_guard BEFORE INSERT OR UPDATE ON technical_solution_revisions FOR EACH ROW EXECUTE FUNCTION validate_technical_solution_ctr_pin();
CREATE TRIGGER technical_solution_final_immutable BEFORE UPDATE OR DELETE ON technical_solution_revisions FOR EACH ROW WHEN (OLD.status='FINAL') EXECUTE FUNCTION protect_commercial_frozen_row();
CREATE TRIGGER cost_decision_pin_guard BEFORE INSERT ON cost_sheet_decisions FOR EACH ROW EXECUTE FUNCTION validate_cost_decision_pins();
CREATE TRIGGER cost_decisions_immutable BEFORE UPDATE OR DELETE ON cost_sheet_decisions FOR EACH ROW EXECUTE FUNCTION protect_commercial_frozen_row();
CREATE TRIGGER cost_lines_immutable BEFORE UPDATE OR DELETE ON cost_sheet_lines FOR EACH ROW EXECUTE FUNCTION protect_commercial_frozen_row();
CREATE TRIGGER policy_evaluations_immutable BEFORE UPDATE OR DELETE ON sales_policy_evaluations FOR EACH ROW EXECUTE FUNCTION protect_commercial_frozen_row();
CREATE TRIGGER policy_evaluation_pin_guard BEFORE INSERT ON sales_policy_evaluations FOR EACH ROW EXECUTE FUNCTION validate_policy_evaluation_pins();
CREATE TRIGGER quote_revision_pin_guard BEFORE INSERT OR UPDATE ON quote_revisions FOR EACH ROW EXECUTE FUNCTION validate_quote_revision_pins();
CREATE TRIGGER quote_revisions_frozen_guard BEFORE UPDATE OR DELETE ON quote_revisions FOR EACH ROW EXECUTE FUNCTION protect_quote_revision();
CREATE TRIGGER quote_issued_snapshots_immutable BEFORE UPDATE OR DELETE ON quote_issued_snapshots FOR EACH ROW EXECUTE FUNCTION protect_commercial_frozen_row();

INSERT INTO permissions(capability,description) VALUES
('opportunity:read','Read opportunities'),('opportunity:create','Create opportunities'),('opportunity:update','Update opportunities'),('opportunity:lifecycle','Change opportunity lifecycle'),
('ctr:read','Read CTRs'),('ctr:create','Create CTRs'),('ctr:update','Update draft CTRs'),('ctr:submit','Submit CTRs'),('ctr:approve','Approve CTRs'),
('technical-solution:read','Read technical solutions'),('technical-solution:create','Create technical solutions'),('technical-solution:update','Update draft technical solutions'),
('cost-model:read','Read cost models'),('cost-model:manage','Manage cost models'),('cost:evaluate','Evaluate costs'),('cost:read','Read cost decisions'),
('sales-policy:read','Read sales policies'),('sales-policy:manage','Manage sales policies'),('sales-policy:evaluate','Evaluate sales policies'),
('quote:read','Read quotes'),('quote:create','Create quotes'),('quote:update','Update draft quotes'),('quote:approve','Approve quotes'),('quote:issue','Issue quotes') ON CONFLICT(capability) DO NOTHING;
