-- E11-E17: immutable, tenant-composite Quote-to-Cash ledger.
CREATE TYPE credit_decision_status AS ENUM('PENDING_APPROVAL','APPROVED','REJECTED','EXPIRED');
CREATE TYPE contract_revision_status AS ENUM('DRAFT','SIGNED','VOID');
CREATE TYPE sales_order_status AS ENUM('RELEASED','CANCELLED');
CREATE TYPE ar_document_type AS ENUM('INVOICE','CREDIT_NOTE');
CREATE TYPE reconciliation_status AS ENUM('COMPLETED','NO_MATCH');

-- Enables exact tenant-composite snapshot pins without mutating historical migrations.
CREATE UNIQUE INDEX quote_issued_snapshots_id_tenant_unique ON quote_issued_snapshots(id,tenant_id);

CREATE TABLE credit_limits(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,customer_id uuid NOT NULL,currency char(3) NOT NULL,amount numeric(24,6) NOT NULL CHECK(amount>=0),effective_at timestamptz NOT NULL,expires_at timestamptz NOT NULL CHECK(expires_at>effective_at),actor_id uuid NOT NULL,canonical_input jsonb NOT NULL,canonical_hash char(64) NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));
CREATE TABLE credit_exposure_snapshots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,customer_id uuid NOT NULL,currency char(3) NOT NULL,scale smallint NOT NULL DEFAULT 6 CHECK(scale=6),receivable_amount numeric(24,6) NOT NULL CHECK(receivable_amount>=0),uninvoiced_order_amount numeric(24,6) NOT NULL CHECK(uninvoiced_order_amount>=0),unapplied_payment_amount numeric(24,6) NOT NULL CHECK(unapplied_payment_amount>=0),exposure_amount numeric(24,6) NOT NULL CHECK(exposure_amount=greatest(0,receivable_amount+uninvoiced_order_amount-unapplied_payment_amount)),canonical_input jsonb NOT NULL,calculation_trace jsonb NOT NULL,canonical_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));
CREATE TABLE credit_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,customer_id uuid NOT NULL,quote_revision_id uuid NOT NULL,quote_snapshot_id uuid NOT NULL,exposure_snapshot_id uuid NOT NULL,credit_limit_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),status credit_decision_status NOT NULL,requested_amount numeric(24,6) NOT NULL CHECK(requested_amount>=0),currency char(3) NOT NULL,approval_required boolean NOT NULL,valid_until timestamptz NOT NULL,canonical_input jsonb NOT NULL,calculation_trace jsonb NOT NULL,canonical_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,customer_id,quote_revision_id,version),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(quote_revision_id,tenant_id) REFERENCES quote_revisions(id,tenant_id),FOREIGN KEY(quote_snapshot_id,tenant_id) REFERENCES quote_issued_snapshots(id,tenant_id),FOREIGN KEY(exposure_snapshot_id,tenant_id) REFERENCES credit_exposure_snapshots(id,tenant_id),FOREIGN KEY(credit_limit_id,tenant_id) REFERENCES credit_limits(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));
CREATE TABLE credit_approvals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,credit_decision_id uuid NOT NULL,decision approval_decision NOT NULL,reason text NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,canonical_hash char(64) NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(credit_decision_id,tenant_id) REFERENCES credit_decisions(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id));
-- A decision is never self-approving: its effective outcome is derived from immutable
-- approval evidence.  This also prevents privileged SQL clients bypassing the command.
ALTER TABLE credit_decisions ADD CONSTRAINT credit_decision_requires_evidence CHECK(status<>'APPROVED');
CREATE UNIQUE INDEX credit_approvals_one_effective_decision ON credit_approvals(tenant_id,credit_decision_id);

CREATE TABLE contracts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,customer_id uuid NOT NULL,opportunity_id uuid NOT NULL,contract_number text NOT NULL,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,contract_number),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(opportunity_id,tenant_id) REFERENCES opportunities(id,tenant_id),FOREIGN KEY(created_by,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE contract_revisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,contract_id uuid NOT NULL,revision integer NOT NULL CHECK(revision>0),quote_revision_id uuid NOT NULL,quote_snapshot_id uuid NOT NULL,status contract_revision_status NOT NULL DEFAULT 'DRAFT',content jsonb NOT NULL,content_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,contract_id,revision),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(contract_id,tenant_id) REFERENCES contracts(id,tenant_id),FOREIGN KEY(quote_revision_id,tenant_id) REFERENCES quote_revisions(id,tenant_id),FOREIGN KEY(quote_snapshot_id,tenant_id) REFERENCES quote_issued_snapshots(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE contract_signature_evidence(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,contract_revision_id uuid NOT NULL,provider text NOT NULL,provider_receipt_id text NOT NULL,payload jsonb NOT NULL,payload_hash char(64) NOT NULL,signed_at timestamptz NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,provider,provider_receipt_id),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(contract_revision_id,tenant_id) REFERENCES contract_revisions(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id));

CREATE TABLE sales_orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,customer_id uuid NOT NULL,opportunity_id uuid NOT NULL,order_number text NOT NULL,quote_revision_id uuid NOT NULL,quote_snapshot_id uuid NOT NULL,credit_decision_id uuid NOT NULL,contract_revision_id uuid NOT NULL,signature_evidence_id uuid NOT NULL,status sales_order_status NOT NULL DEFAULT 'RELEASED',currency char(3) NOT NULL,total numeric(24,6) NOT NULL CHECK(total>0),canonical_input jsonb NOT NULL,canonical_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,order_number),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(opportunity_id,tenant_id) REFERENCES opportunities(id,tenant_id),FOREIGN KEY(quote_revision_id,tenant_id) REFERENCES quote_revisions(id,tenant_id),FOREIGN KEY(quote_snapshot_id,tenant_id) REFERENCES quote_issued_snapshots(id,tenant_id),FOREIGN KEY(credit_decision_id,tenant_id) REFERENCES credit_decisions(id,tenant_id),FOREIGN KEY(contract_revision_id,tenant_id) REFERENCES contract_revisions(id,tenant_id),FOREIGN KEY(signature_evidence_id,tenant_id) REFERENCES contract_signature_evidence(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));
CREATE TABLE sales_order_lines(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,sales_order_id uuid NOT NULL,line_number integer NOT NULL CHECK(line_number>0),description text NOT NULL,quantity numeric(24,6) NOT NULL CHECK(quantity>0),unit_price numeric(24,6) NOT NULL CHECK(unit_price>=0),total numeric(24,6) NOT NULL CHECK(total=trunc(quantity*unit_price,6)),UNIQUE(id,tenant_id),UNIQUE(tenant_id,sales_order_id,line_number),FOREIGN KEY(sales_order_id,tenant_id) REFERENCES sales_orders(id,tenant_id));

CREATE FUNCTION validate_sales_order_total() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE oid uuid; tid uuid; expected numeric(24,6); actual numeric(24,6); BEGIN
 oid:=CASE WHEN TG_TABLE_NAME='sales_orders' THEN NEW.id ELSE NEW.sales_order_id END;
 tid:=CASE WHEN TG_TABLE_NAME='sales_orders' THEN NEW.tenant_id ELSE NEW.tenant_id END;
 SELECT total INTO expected FROM sales_orders WHERE id=oid AND tenant_id=tid;
 SELECT sum(total) INTO actual FROM sales_order_lines WHERE sales_order_id=oid AND tenant_id=tid;
 IF expected IS NULL OR actual IS NULL OR actual<>expected THEN RAISE EXCEPTION 'sales order requires lines totaling order total'; END IF;
 RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER sales_order_total_from_order AFTER INSERT ON sales_orders DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_sales_order_total();
CREATE CONSTRAINT TRIGGER sales_order_total_from_lines AFTER INSERT ON sales_order_lines DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION validate_sales_order_total();

CREATE TABLE ar_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,customer_id uuid NOT NULL,sales_order_id uuid,document_number text NOT NULL,document_type ar_document_type NOT NULL,currency char(3) NOT NULL,scale smallint NOT NULL DEFAULT 6 CHECK(scale=6),amount numeric(24,6) NOT NULL CHECK(amount>0),due_at timestamptz NOT NULL,canonical_input jsonb NOT NULL,canonical_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,posted_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,document_number),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(sales_order_id,tenant_id) REFERENCES sales_orders(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));
CREATE TABLE ar_open_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,ar_document_id uuid NOT NULL,customer_id uuid NOT NULL,currency char(3) NOT NULL,original_amount numeric(24,6) NOT NULL CHECK(original_amount>0),due_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,ar_document_id),FOREIGN KEY(ar_document_id,tenant_id) REFERENCES ar_documents(id,tenant_id),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));
CREATE TABLE bank_payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,customer_id uuid,currency char(3) NOT NULL,scale smallint NOT NULL DEFAULT 6 CHECK(scale=6),amount numeric(24,6) NOT NULL CHECK(amount>0),received_at timestamptz NOT NULL,bank_reference text NOT NULL,raw_payload jsonb NOT NULL,raw_payload_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,bank_reference),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(customer_id,tenant_id) REFERENCES customers(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));
CREATE TABLE reconciliation_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,status reconciliation_status NOT NULL,input jsonb NOT NULL,calculation_trace jsonb NOT NULL,input_hash char(64) NOT NULL,result_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,input_hash),UNIQUE(tenant_id,idempotency_key),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id));
CREATE TABLE allocation_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,reconciliation_run_id uuid,bank_payment_id uuid NOT NULL,ar_open_item_id uuid NOT NULL,currency char(3) NOT NULL,amount numeric(24,6) NOT NULL CHECK(amount>0),allocation_order integer NOT NULL CHECK(allocation_order>0),canonical_hash char(64) NOT NULL,actor_id uuid NOT NULL,correlation_id uuid NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,tenant_id),UNIQUE(tenant_id,idempotency_key),UNIQUE(tenant_id,reconciliation_run_id,allocation_order),FOREIGN KEY(reconciliation_run_id,tenant_id) REFERENCES reconciliation_runs(id,tenant_id),FOREIGN KEY(bank_payment_id,tenant_id) REFERENCES bank_payments(id,tenant_id),FOREIGN KEY(ar_open_item_id,tenant_id) REFERENCES ar_open_items(id,tenant_id),FOREIGN KEY(actor_id,tenant_id) REFERENCES employees(id,company_id),FOREIGN KEY(currency) REFERENCES commercial_currencies(code));

CREATE VIEW ar_open_item_balances AS SELECT oi.*,oi.original_amount-coalesce(sum(a.amount),0) AS remaining_amount FROM ar_open_items oi LEFT JOIN allocation_entries a ON a.tenant_id=oi.tenant_id AND a.ar_open_item_id=oi.id GROUP BY oi.id;
CREATE VIEW bank_payment_balances AS SELECT p.*,p.amount-coalesce(sum(a.amount),0) AS remaining_amount FROM bank_payments p LEFT JOIN allocation_entries a ON a.tenant_id=p.tenant_id AND a.bank_payment_id=p.id GROUP BY p.id;
CREATE VIEW effective_credit_decisions AS SELECT d.*,
 CASE WHEN d.valid_until<=now() THEN 'EXPIRED'::credit_decision_status
      WHEN a.decision='APPROVED' THEN 'APPROVED'::credit_decision_status
      WHEN a.decision='REJECTED' THEN 'REJECTED'::credit_decision_status
      ELSE 'PENDING_APPROVAL'::credit_decision_status END AS effective_status,
 a.id AS approval_id,a.actor_id AS approved_by,a.created_at AS decided_at
 FROM credit_decisions d LEFT JOIN credit_approvals a ON a.tenant_id=d.tenant_id AND a.credit_decision_id=d.id;

CREATE FUNCTION validate_qtc_pins() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE q record; BEGIN
 IF TG_TABLE_NAME='credit_decisions' THEN SELECT r.status,r.valid_until,s.quote_revision_id INTO q FROM quote_revisions r JOIN quote_issued_snapshots s ON s.tenant_id=r.tenant_id AND s.id=NEW.quote_snapshot_id WHERE r.tenant_id=NEW.tenant_id AND r.id=NEW.quote_revision_id; IF q.status IS DISTINCT FROM 'ISSUED' OR q.valid_until<=now() OR q.quote_revision_id IS DISTINCT FROM NEW.quote_revision_id THEN RAISE EXCEPTION 'credit decision requires exact unexpired issued quote snapshot'; END IF;
 ELSIF TG_TABLE_NAME='contract_revisions' THEN IF NOT EXISTS(SELECT 1 FROM quote_issued_snapshots s WHERE s.tenant_id=NEW.tenant_id AND s.id=NEW.quote_snapshot_id AND s.quote_revision_id=NEW.quote_revision_id) THEN RAISE EXCEPTION 'contract requires exact issued quote snapshot'; END IF;
 ELSIF TG_TABLE_NAME='sales_orders' THEN IF NOT EXISTS(SELECT 1 FROM quote_revisions qr JOIN quotes q ON q.id=qr.quote_id AND q.tenant_id=qr.tenant_id JOIN opportunities o ON o.id=q.opportunity_id AND o.tenant_id=q.tenant_id JOIN quote_issued_snapshots qs ON qs.tenant_id=qr.tenant_id AND qs.id=NEW.quote_snapshot_id AND qs.quote_revision_id=qr.id JOIN effective_credit_decisions cd ON cd.tenant_id=qr.tenant_id AND cd.id=NEW.credit_decision_id AND cd.quote_revision_id=qr.id AND cd.quote_snapshot_id=qs.id JOIN contracts c ON c.tenant_id=qr.tenant_id AND c.customer_id=cd.customer_id AND c.opportunity_id=o.id JOIN contract_revisions cr ON cr.tenant_id=c.tenant_id AND cr.contract_id=c.id AND cr.id=NEW.contract_revision_id AND cr.quote_revision_id=qr.id AND cr.quote_snapshot_id=qs.id JOIN contract_signature_evidence se ON se.tenant_id=cr.tenant_id AND se.id=NEW.signature_evidence_id AND se.contract_revision_id=cr.id WHERE qr.tenant_id=NEW.tenant_id AND qr.id=NEW.quote_revision_id AND qr.status='ISSUED' AND qr.valid_until>now() AND cd.effective_status='APPROVED' AND cd.valid_until>now() AND NEW.customer_id=cd.customer_id AND NEW.customer_id=c.customer_id AND NEW.opportunity_id=o.id AND NEW.currency=qr.currency AND NEW.total=qr.total) THEN RAISE EXCEPTION 'order commercial graph is stale, unapproved, unsigned, or inconsistent'; END IF; END IF; RETURN NEW; END $$;
CREATE TRIGGER credit_decision_pins BEFORE INSERT ON credit_decisions FOR EACH ROW EXECUTE FUNCTION validate_qtc_pins();
CREATE TRIGGER contract_revision_pins BEFORE INSERT ON contract_revisions FOR EACH ROW EXECUTE FUNCTION validate_qtc_pins();
CREATE TRIGGER sales_order_pins BEFORE INSERT ON sales_orders FOR EACH ROW EXECUTE FUNCTION validate_qtc_pins();

CREATE FUNCTION enforce_credit_approval_separation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF EXISTS(SELECT 1 FROM credit_decisions d WHERE d.id=NEW.credit_decision_id AND d.tenant_id=NEW.tenant_id AND d.actor_id=NEW.actor_id)
 THEN RAISE EXCEPTION 'credit evaluator cannot approve own decision'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER credit_approval_actor_separation BEFORE INSERT ON credit_approvals FOR EACH ROW EXECUTE FUNCTION enforce_credit_approval_separation();

CREATE FUNCTION validate_allocation_remaining() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE pb numeric(24,6); ob numeric(24,6); pc char(3); oc char(3); BEGIN SELECT amount-coalesce((SELECT sum(amount) FROM allocation_entries WHERE tenant_id=NEW.tenant_id AND bank_payment_id=NEW.bank_payment_id),0),currency INTO pb,pc FROM bank_payments WHERE tenant_id=NEW.tenant_id AND id=NEW.bank_payment_id FOR UPDATE; SELECT original_amount-coalesce((SELECT sum(amount) FROM allocation_entries WHERE tenant_id=NEW.tenant_id AND ar_open_item_id=NEW.ar_open_item_id),0),currency INTO ob,oc FROM ar_open_items WHERE tenant_id=NEW.tenant_id AND id=NEW.ar_open_item_id FOR UPDATE; IF pc IS DISTINCT FROM NEW.currency OR oc IS DISTINCT FROM NEW.currency THEN RAISE EXCEPTION 'allocation currency mismatch'; END IF; IF NEW.amount>pb OR NEW.amount>ob THEN RAISE EXCEPTION 'allocation exceeds remaining balance'; END IF; RETURN NEW; END $$;
CREATE TRIGGER allocation_remaining BEFORE INSERT ON allocation_entries FOR EACH ROW EXECUTE FUNCTION validate_allocation_remaining();

CREATE FUNCTION derive_credit_exposure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 SELECT greatest(0,coalesce(sum(CASE WHEN d.document_type='INVOICE' THEN b.remaining_amount ELSE -b.remaining_amount END),0)) INTO NEW.receivable_amount FROM ar_open_item_balances b JOIN ar_documents d ON d.id=b.ar_document_id AND d.tenant_id=b.tenant_id WHERE b.tenant_id=NEW.tenant_id AND b.customer_id=NEW.customer_id AND b.currency=NEW.currency;
 SELECT coalesce(sum(o.total-coalesce((SELECT sum(d.amount) FROM ar_documents d WHERE d.tenant_id=o.tenant_id AND d.sales_order_id=o.id AND d.document_type='INVOICE'),0)),0) INTO NEW.uninvoiced_order_amount FROM sales_orders o WHERE o.tenant_id=NEW.tenant_id AND o.customer_id=NEW.customer_id AND o.currency=NEW.currency AND o.status='RELEASED';
 SELECT coalesce(sum(b.remaining_amount),0) INTO NEW.unapplied_payment_amount FROM bank_payment_balances b WHERE b.tenant_id=NEW.tenant_id AND b.customer_id=NEW.customer_id AND b.currency=NEW.currency;
 NEW.exposure_amount:=greatest(0,NEW.receivable_amount+NEW.uninvoiced_order_amount-NEW.unapplied_payment_amount);
 NEW.canonical_input:=jsonb_build_object('customerId',NEW.customer_id,'currency',NEW.currency,'receivableAmount',NEW.receivable_amount,'uninvoicedOrderAmount',NEW.uninvoiced_order_amount,'unappliedPaymentAmount',NEW.unapplied_payment_amount);
 NEW.calculation_trace:=jsonb_build_object('formula','greatest(0, receivable + uninvoiced orders - unapplied payments)','scale',6);
 NEW.canonical_hash:=encode(digest(NEW.canonical_input::text,'sha256'),'hex');
 RETURN NEW; END $$;
CREATE TRIGGER credit_exposure_server_derived BEFORE INSERT ON credit_exposure_snapshots FOR EACH ROW EXECUTE FUNCTION derive_credit_exposure();

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['credit_limits','credit_exposure_snapshots','credit_decisions','credit_approvals','contracts','contract_revisions','contract_signature_evidence','sales_orders','sales_order_lines','ar_documents','ar_open_items','bank_payments','reconciliation_runs','allocation_entries'] LOOP EXECUTE format('CREATE TRIGGER %I_immutable BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION protect_commercial_frozen_row()',t,t); END LOOP; END $$;

INSERT INTO permissions(capability,description) VALUES
('credit:read','Read credit evidence'),('credit:evaluate','Evaluate credit'),('credit:approve','Approve credit'),
('contract:read','Read contracts'),('contract:revise','Create contract revisions'),('contract:sign','Capture signature evidence'),
('sales-order:read','Read sales orders'),('sales-order:create','Release sales orders'),
('ar:read','Read accounts receivable'),('ar:post','Post AR documents'),
('bank-payment:read','Read bank payments'),('bank-payment:intake','Intake bank payments'),
('reconciliation:read','Read reconciliation evidence'),('reconciliation:run','Run reconciliation'),('allocation:create','Allocate payments') ON CONFLICT(capability) DO NOTHING;
