import type { AuditEvent, AuditSink, AuthorizationContext, EmployeeRepository, OrganizationRepository } from '@kingturf/domain';
import { DomainError, normalizeEmail } from '@kingturf/domain';
import type { Database, SqlClient } from '@kingturf/database';
import type { DataScope, EmployeeDto, OrganizationDto, PermissionKey } from '@kingturf/types';
import type { CredentialStore } from './security.ts';
import { dataScopeSql } from './policy.ts';

type OrganizationRow = { id: string; owner_organization_id: string; parent_id: string | null; code: string; name: string; locale: string; currency: string; active: boolean; version: number };
type EmployeeRow = { id: string; company_id: string; organization_id: string; employee_number: string; display_name: string; normalized_email: string; active: boolean; version: number };
const organization = (row: OrganizationRow): OrganizationDto => ({ id: row.id, ownerOrganizationId: row.owner_organization_id, parentId: row.parent_id, code: row.code, name: row.name, locale: row.locale, currency: row.currency, active: row.active, version: row.version });
const employee = (row: EmployeeRow): EmployeeDto => ({ id: row.id, companyId: row.company_id, organizationId: row.organization_id, employeeNumber: row.employee_number, displayName: row.display_name, email: row.normalized_email, active: row.active, version: row.version });

export class PostgresOrganizationRepository implements OrganizationRepository {
  public constructor(private readonly db: SqlClient) {}
  public async create(input: Omit<OrganizationDto, 'id' | 'version'>, actor: Readonly<{ employeeId: string; companyId: string }>): Promise<OrganizationDto> {
    if (input.ownerOrganizationId !== actor.companyId) throw new DomainError('forbidden', 'Organization ownership must match the actor company');
    const result = await this.db.query<OrganizationRow>('INSERT INTO organizations(owner_organization_id,parent_id,code,name,organization_type,locale,currency,active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING *', [input.ownerOrganizationId, input.parentId, input.code, input.name, input.parentId ? 'DEPARTMENT' : 'COMPANY', input.locale, input.currency, input.active, actor.employeeId]);
    const created = result.rows[0];
    if (!created) throw new DomainError('invalid_request', 'Organization could not be created');
    return organization(created);
  }
  public async findById(id: string, companyId: string): Promise<OrganizationDto | null> { const result = await this.db.query<OrganizationRow>('SELECT * FROM organizations WHERE id=$1 AND owner_organization_id=$2 AND deleted_at IS NULL', [id, companyId]); return result.rows[0] ? organization(result.rows[0]) : null; }
  public async list(companyId: string): Promise<readonly OrganizationDto[]> { return (await this.db.query<OrganizationRow>('SELECT * FROM organizations WHERE owner_organization_id=$1 AND deleted_at IS NULL ORDER BY code', [companyId])).rows.map(organization); }
  public async update(id: string, companyId: string, patch: Partial<Pick<OrganizationDto, 'name' | 'parentId' | 'active' | 'locale' | 'currency'>>, version: number, actor: Readonly<{ employeeId: string }>): Promise<OrganizationDto> {
    const result = await this.db.query<OrganizationRow>('UPDATE organizations SET name=COALESCE($3,name),parent_id=COALESCE($4,parent_id),active=COALESCE($5,active),locale=COALESCE($6,locale),currency=COALESCE($7,currency),version=version+1,updated_at=now(),updated_by=$8 WHERE id=$1 AND owner_organization_id=$2 AND version=$9 AND deleted_at IS NULL RETURNING *', [id, companyId, patch.name ?? null, patch.parentId ?? null, patch.active ?? null, patch.locale ?? null, patch.currency ?? null, actor.employeeId, version]);
    if (!result.rows[0]) throw new DomainError('conflict', 'Organization version is stale or record is unavailable'); return organization(result.rows[0]);
  }
}
export class PostgresEmployeeRepository implements EmployeeRepository {
  public constructor(private readonly db: SqlClient) {}
  public async create(input: Omit<EmployeeDto, 'id' | 'version'>, actor: Readonly<{ employeeId: string; companyId: string }>): Promise<EmployeeDto> { if (input.companyId !== actor.companyId) throw new DomainError('forbidden', 'Company mismatch'); const result = await this.db.query<EmployeeRow>('INSERT INTO employees(company_id,organization_id,employee_number,display_name,normalized_email,active,created_by,updated_by) SELECT $1,$2,$3,$4,$5,$6,$7,$7 WHERE EXISTS(SELECT 1 FROM organizations WHERE id=$2 AND owner_organization_id=$1 AND active AND deleted_at IS NULL) RETURNING *', [input.companyId,input.organizationId,input.employeeNumber,input.displayName,normalizeEmail(input.email),input.active,actor.employeeId]); if (!result.rows[0]) throw new DomainError('invalid_request','Organization is not an active member of the company'); return employee(result.rows[0]); }
  async #scoped(scopes: readonly DataScope[], actorId: string, startParameter=3): Promise<{ predicate: string; values: readonly unknown[] }> { const actor = await this.db.query<{ organization_id: string }>('SELECT organization_id FROM employees WHERE id=$1', [actorId]); const organizationId = actor.rows[0]?.organization_id ?? ''; const scope = dataScopeSql(scopes, 'e', startParameter); return { predicate: scope.sql, values: scope.values.map((key) => key === 'companyId' ? undefined : key === 'actorId' ? actorId : organizationId) }; }
  public async findById(id: string, companyId: string, scopes: readonly DataScope[], actorId: string): Promise<EmployeeDto | null> { const scoped = await this.#scoped(scopes, actorId); const values = scoped.values.map((value) => value ?? companyId); const result = await this.db.query<EmployeeRow>(`SELECT e.* FROM employees e WHERE e.id=$1 AND e.company_id=$2 AND e.deleted_at IS NULL AND ${scoped.predicate}`, [id,companyId,...values]); return result.rows[0] ? employee(result.rows[0]) : null; }
  public async list(companyId: string, scopes: readonly DataScope[], actorId: string): Promise<readonly EmployeeDto[]> { const scoped = await this.#scoped(scopes, actorId); const shifted = scoped.predicate.replaceAll(/\$(\d+)/gu, (_, n: string) => `$${String(Number(n)-1)}`); const values = scoped.values.map((value) => value ?? companyId); return (await this.db.query<EmployeeRow>(`SELECT e.* FROM employees e WHERE e.company_id=$1 AND e.deleted_at IS NULL AND ${shifted} ORDER BY e.employee_number`, [companyId,...values])).rows.map(employee); }
  public async update(id: string, companyId: string, patch: Partial<Pick<EmployeeDto,'displayName'|'email'|'organizationId'|'active'>>, version: number, actor: Readonly<{employeeId:string}>, scopes:readonly DataScope[]): Promise<EmployeeDto> { const scoped=await this.#scoped(scopes,actor.employeeId,9);const values=scoped.values.map(value=>value??companyId);const result=await this.db.query<EmployeeRow>(`UPDATE employees e SET display_name=COALESCE($3,e.display_name),normalized_email=COALESCE($4,e.normalized_email),organization_id=COALESCE($5,e.organization_id),active=COALESCE($6,e.active),version=e.version+1,updated_at=now(),updated_by=$7 WHERE e.id=$1 AND e.company_id=$2 AND e.version=$8 AND e.deleted_at IS NULL AND ${scoped.predicate} AND ($5::uuid IS NULL OR EXISTS(SELECT 1 FROM organizations o WHERE o.id=$5 AND o.owner_organization_id=$2 AND o.active AND o.deleted_at IS NULL)) RETURNING e.*`,[id,companyId,patch.displayName??null,patch.email?normalizeEmail(patch.email):null,patch.organizationId??null,patch.active??null,actor.employeeId,version,...values]); if(!result.rows[0]) throw new DomainError('conflict','Employee version is stale, outside the granted data scope, or record is unavailable'); return employee(result.rows[0]); }
}

export class PostgresSecurityStore implements CredentialStore, AuditSink {
  public constructor(private readonly database: Database) {}
  public async findForLogin(login: string) { const result=await this.database.query<{identity_id:string;employee_id:string;company_id:string;password_hash:string;identity_active:boolean;employee_active:boolean;member_active:boolean}>('SELECT i.id identity_id,e.id employee_id,e.company_id,pc.password_hash,i.active identity_active,e.active employee_active,COALESCE(bool_or(om.active),false) member_active FROM identities i JOIN password_credentials pc ON pc.identity_id=i.id JOIN employees e ON e.id=i.employee_id LEFT JOIN organization_memberships om ON om.employee_id=e.id WHERE i.login_name=$1 AND i.deleted_at IS NULL AND e.deleted_at IS NULL GROUP BY i.id,e.id,pc.password_hash',[login]); const r=result.rows[0]; return r?{identityId:r.identity_id,employeeId:r.employee_id,companyId:r.company_id,passwordHash:r.password_hash,identityActive:r.identity_active,employeeActive:r.employee_active,memberActive:r.member_active}:null; }
  public async createSession(input: Readonly<{identityId:string;organizationId:string;tokenHash:string;expiresAt:Date}>): Promise<void> { await this.database.query('INSERT INTO sessions(identity_id,organization_id,token_hash,expires_at) VALUES($1,$2,$3,$4)',[input.identityId,input.organizationId,input.tokenHash,input.expiresAt]); }
  public async revokeSession(hash:string):Promise<boolean>{return (await this.database.query('UPDATE sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL',[hash])).rowCount===1;}
  public async resolveSession(hash:string,now:Date):Promise<AuthorizationContext|null>{return this.database.transaction(async tx=>{const base=await tx.query<{employee_id:string;company_id:string}>('SELECT e.id employee_id,e.company_id FROM sessions s JOIN identities i ON i.id=s.identity_id AND i.active AND i.deleted_at IS NULL JOIN employees e ON e.id=i.employee_id AND e.active AND e.deleted_at IS NULL JOIN organization_memberships om ON om.employee_id=e.id AND om.organization_id=e.company_id AND om.active WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>$2 AND s.organization_id=e.company_id LIMIT 1',[hash,now]);const actor=base.rows[0];if(!actor)return null;const grants=await tx.query<{capability:PermissionKey;field_allowlist:string[]|null;data_scopes:DataScope[]}>('SELECT p.capability,g.field_allowlist,g.data_scopes FROM employee_role_assignments era JOIN roles r ON r.id=era.role_id AND r.deleted_at IS NULL JOIN role_permission_grants g ON g.role_id=r.id JOIN permissions p ON p.id=g.permission_id WHERE era.employee_id=$1 AND r.organization_id=$2',[actor.employee_id,actor.company_id]);const permissions=new Map<PermissionKey,{fields:readonly string[]|null;scopes:readonly DataScope[]}>();for(const g of grants.rows){const previous=permissions.get(g.capability);const scopes=[...new Set([...(previous?.scopes??[]),...g.data_scopes])].sort();const fields=previous?.fields===null||g.field_allowlist===null?null:[...new Set([...(previous?.fields??[]),...g.field_allowlist])].sort();permissions.set(g.capability,{fields,scopes});}return{actor:{employeeId:actor.employee_id,companyId:actor.company_id},permissions};});}
  public async replacePasswordForEmployee(employeeId:string,passwordHash:string):Promise<void>{const result=await this.database.query('UPDATE password_credentials pc SET password_hash=$2,changed_at=now(),updated_by=$1 FROM identities i WHERE pc.identity_id=i.id AND i.employee_id=$1',[employeeId,passwordHash]);if(result.rowCount!==1)throw new DomainError('not_found','Credential not found');}
  public async record(event:AuditEvent):Promise<void>{await this.database.query('INSERT INTO audit_events(action,outcome,actor_id,organization_id,target_type,target_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[event.action,event.outcome,event.actorId,event.organizationId,event.targetType,event.targetId,event.correlationId,event.metadata??{}]);}
}
